### ISSUE TITLE
Where does the domain for the cross-sectional area expansion start?

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/HYDRAD#103]
This is less of an issue and more of a question. When specifying a cross-sectional area variation via the piecewise polynomial fits, is it assumed that the domain for this expansion includes the chromosphere as well or does it only start at the bottom of the transition region at one footpoint and end at the bottom of the transition region at the other footpoint? I have assumed the former, i.e. that the domain of the expansion covers computational domain. The same question could also be applied to the piecewise polynomial fits for the gravitational acceleration profile.

**Comment by jwreep** [comment]
From the photosphere at s=0.  

The code uses a normalized loop coordinate = (s / 2L) for these functions.

**Comment by wtbarnes** [comment]
Thanks @jwreep!
