### ISSUE TITLE
Mass terms in `.trm` files have same sign?

### ISSUE THREAD

**Issue by jwreep** [rice-solar-physics/HYDRAD#105]
$\frac{\partial \rho}{\partial{t}} = - \frac{1}{A} \frac{\partial}{\partial s} \Big(A \rho v \Big)$

I'm looking through `.trm` files and noticed that the two terms in the mass equation have the same sign consistently, when presumably they should be opposite signs?  I've looked through a bunch of files and haven't spotted any case where they're opposite.

Just grabbing some arbitrary lines from one arbitrary file, for example:
```
5.46875000e+05
-1.21919564e-09	-1.21919564e-09
1.21389731e-03	-1.38148788e-06	1.15622388e-02	-1.03976880e-02	-3.57522532e-17	5.07279470e-05
-7.63401265e+03	-3.63874755e+01	-1.71262375e-07	0.00000000e+00	-7.59577976e+03	1.00000000e-300	-1.00000000e-300	-1.82232344e+00	0.00000000e+00	0.00000000e+00	-2.30894158e-02
6.36519271e+03	-1.22724583e+03	-1.02215855e-06	-5.22762701e+00	7.59577976e+03	1.00000000e-300	0.00000000e+00	1.82232344e+00	7.04864451e-12	6.40857857e-02	0.00000000e+00
7.81250000e+05
5.34624464e-11	5.34624464e-11
-1.16114053e-04	-4.01806899e-07	1.03089390e-02	-1.03198999e-02	-1.44092900e-14	-1.04751313e-04
-6.35021957e+03	6.12377387e+00	1.74676873e-07	0.00000000e+00	-6.35282595e+03	1.00000000e-300	-1.00000000e-300	-3.49813909e+00	0.00000000e+00	0.00000000e+00	-1.92587461e-02
6.40211765e+03	5.88812993e+01	2.47599558e-06	-1.30106069e+01	6.35282595e+03	1.00000000e-300	0.00000000e+00	3.49813909e+00	-1.06103923e-11	-7.71354218e-02	0.00000000e+00
1.09375000e+06
1.17428870e-09	1.17428870e-09
-1.39990824e-03	7.33780876e-07	8.85175319e-03	-1.02209028e-02	1.44665902e-15	-3.14923865e-05
5.58445692e+03	2.99906349e+01	1.95127144e-08	0.00000000e+00	5.55468284e+03	1.00000000e-300	-1.00000000e-300	-1.99785151e-01	0.00000000e+00	0.00000000e+00	-1.67683147e-02
```

The relevant line in HYDRAD:
https://github.com/rice-solar-physics/HYDRAD/blob/0fa1f9949540e6b9379548c72a030621fdee381d/HYDRAD/source/eqns.cpp#L2310-L2311
This should have a minus sign, no?  There might also be a sign error, then, in the calculation of the velocity?

**Comment by sjbradshaw** [comment]
No, it’s fine.

 

Mass continuity:

 

d(rho)/dt + d(rho . v)/ds = 0

 

So:

 

d(rho)/dt = - d(rho . v)/ds = 0

 

So, d(rho)/dt is simply equal to -d(rho . v)/ds’

 

 

 

 

From: Jeffrey Reep ***@***.***> 
Sent: Tuesday, May 21, 2024 12:44 PM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Mass terms in `.trm` files have same sign? (Issue #105)

 

$\frac{\partial \rho}{\partial{t}} = - \frac{1}{A} \frac{\partial}{\partial s} \Big(A \rho v \Big)$

I'm looking through .trm files and noticed that the two terms in the mass equation have the same sign consistently, when presumably they should be opposite signs? I've looked through a bunch of files and haven't spotted any case where they're opposite.

Just grabbing some arbitrary lines from one arbitrary file, for example:

5.46875000e+05
-1.21919564e-09 -1.21919564e-09
1.21389731e-03 -1.38148788e-06 1.15622388e-02 -1.03976880e-02 -3.57522532e-17 5.07279470e-05
-7.63401265e+03 -3.63874755e+01 -1.71262375e-07 0.00000000e+00 -7.59577976e+03 1.00000000e-300 -1.00000000e-300       -1.82232344e+00        0.00000000e+00 0.00000000e+00 -2.30894158e-02
6.36519271e+03 -1.22724583e+03 -1.02215855e-06 -5.22762701e+00        7.59577976e+03 1.00000000e-300 0.00000000e+00 1.82232344e+00        7.04864451e-12 6.40857857e-02 0.00000000e+00
7.81250000e+05
5.34624464e-11 5.34624464e-11
-1.16114053e-04 -4.01806899e-07 1.03089390e-02 -1.03198999e-02 -1.44092900e-14 -1.04751313e-04
-6.35021957e+03 6.12377387e+00 1.74676873e-07 0.00000000e+00 -6.35282595e+03 1.00000000e-300 -1.00000000e-300       -3.49813909e+00        0.00000000e+00 0.00000000e+00 -1.92587461e-02
6.40211765e+03 5.88812993e+01 2.47599558e-06 -1.30106069e+01        6.35282595e+03 1.00000000e-300 0.00000000e+00 3.49813909e+00 -1.06103923e-11 -7.71354218e-02 0.00000000e+00
1.09375000e+06
1.17428870e-09 1.17428870e-09
-1.39990824e-03 7.33780876e-07 8.85175319e-03 -1.02209028e-02        1.44665902e-15 -3.14923865e-05
5.58445692e+03 2.99906349e+01 1.95127144e-08 0.00000000e+00        5.55468284e+03 1.00000000e-300 -1.00000000e-300       -1.99785151e-01 0.00000000e+00 0.00000000e+00 -1.67683147e-02

The relevant line in HYDRAD:
https://github.com/rice-solar-physics/HYDRAD/blob/0fa1f9949540e6b9379548c72a030621fdee381d/HYDRAD/source/eqns.cpp#L2310-L2311
This should have a minus sign, no? There might also be a sign error, then, in the calculation of the velocity?

**Comment by jwreep** [comment]
So the minus sign is included in the definition of the term?  Alright, that's fine, just counterintuitive to me.

**Comment by sjbradshaw** [comment]
Basically, yes.

 

The first quantity on each line in the .trm file is just the sum of the terms on the right-hand side.

 

Suppose, for example, that the rate of change of energy only depended on the radiation:

 

dE/dt = -R

 

Radiation is always a loss term (thus, negative), which means that dE/dt would also always be negative. Consequently, the first and second quantities in the corresponding line in the .trm file would both be negative.

 

e.g.

 

[Position]

[dE/dt (=-R)] [-R]
