### ISSUE TITLE
Calculation of advection with area expansion?

### ISSUE THREAD

**Issue by jwreep** [rice-solar-physics/HYDRAD#107]
Might be that I'm missing something obvious as always, but I'm wondering if there's a potential issue in the calculation of the advection of the conserved quantities when there's an area expansion.  For example, for rho, the code is essentially (starting on line 2283 in eqns.cpp):

```
fCrossSection[0] = CalculateCrossSection( CellProperties.s[0]/Params.L );
fCrossSection[1] = CalculateCrossSection( CellProperties.s[1]/Params.L );
fCrossSection[2] = CalculateCrossSection( CellProperties.s[2]/Params.L );
fCellVolume = fCrossSection[1] * CellProperties.cell_width;
LowerValue = CellProperties.rho[0] * CellProperties.v[0];
UpperValue = CellProperties.rho[2] * CellProperties.v[2];
CellProperties.rho_term[0] = - ( UpperValue - LowerValue ) / fCellVolume;
CellProperties.drhobydt = CellProperties.rho_term[0];
```

which seems to be 

<img width="300" alt="current" src="https://github.com/user-attachments/assets/1637ab94-40e9-4e8c-8189-806f46a7af97">

Should it be this?

<img width="350" alt="possible" src="https://github.com/user-attachments/assets/33562692-e70c-4fc8-baf8-8257384eb549">

That is, change the numerator as such:
```
LowerValue = CellProperties.rho[0] * CellProperties.v[0] * fCrossSection[0];
UpperValue = CellProperties.rho[2] * CellProperties.v[2] * fCrossSection[2];
```

Or what I am missing?

**Comment by sjbradshaw** [comment]
It’s okay. The advected quantities are actually pre-multiplied by the cross-section before the values (Q1, Q2, etc.) used for the advection scheme (Barton’s method) are calculated. See lines 1642 – 1645 in eqns.cpp, for example.

 

 

From: Jeffrey Reep ***@***.***> 
Sent: Monday, August 19, 2024 10:27 PM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Calculation of advection with area expansion? (Issue #107)

 

Might be that I'm missing something obvious as always, but I'm wondering if there's a potential issue in the calculation of the advection of the conserved quantities when there's an area expansion. For example, for rho, the code is essentially (starting on line 2283 in eqns.cpp):

fCrossSection[0] = CalculateCrossSection( CellProperties.s[0]/Params.L );
fCrossSection[1] = CalculateCrossSection( CellProperties.s[1]/Params.L );
fCrossSection[2] = CalculateCrossSection( CellProperties.s[2]/Params.L );
fCellVolume = fCrossSection[1] * CellProperties.cell_width;
LowerValue = CellProperties.rho[0] * CellProperties.v[0];
UpperValue = CellProperties.rho[2] * CellProperties.v[2];
CellProperties.rho_term[0] = - ( UpperValue - LowerValue ) / fCellVolume;
CellProperties.drhobydt = CellProperties.rho_term[0];

which seems to be

current.png (view on web) <https://github.com/user-attachments/assets/1637ab94-40e9-4e8c-8189-806f46a7af97>  

Should it be this?

possible.png (view on web) <https://github.com/user-attachments/assets/33562692-e70c-4fc8-baf8-8257384eb549>  

That is, change the numerator as such:

LowerValue = CellProperties.rho[0] * CellProperties.v[0] * fCrossSection[0];
UpperValue = CellProperties.rho[2] * CellProperties.v[2] * fCrossSection[2];

Or what I am missing?

**Comment by jwreep** [comment]
Aha!  That's what I'm missing.  Thank you, Steve!
