### ISSUE TITLE
Using only background heating results in loop collapsing

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/HYDRAD#94]
For a 50 Mm loop with zero heating events (using only background heating as determined by the initial conditions solver), and allowing the simulation to evolve for 500 s, I find that the loop structure collapses after about 150-200 s. I would expect that the loop structure would be maintained at approximately the equilibrium configuration. I've attached a plot below that shows this:

![image](https://user-images.githubusercontent.com/8676141/159611013-cd77830d-eb33-4de7-b392-7294b1ddfe8d.png)

I'm sure I've omitted or misconfigured some input parameter, but I cannot work out which one. I've iterated over all refinement levels (this example uses max refinement level of 12) to ensure that that is not the issue. This is for a semi-circular configuration with no inclination and no exapansion. I've attached the directory for run here as well.

[steady-run.zip](https://github.com/rice-solar-physics/HYDRAD/files/8329197/steady-run.zip)

**Comment by sjbradshaw** [comment]
Is the only parameter that you change the loop length?

 

I’ve just run a 2L = 50 Mm loop, background heating only, and it remains perfectly stable… Are you sure the background heating is being applied?

 

 

 

From: Will Barnes ***@***.***> 
Sent: Tuesday, March 22, 2022 9:28 PM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Using only background heating results in loop collapsing (Issue #94)

 

For a 50 Mm loop with zero heating events (using only background heating as determined by the initial conditions solver), and allowing the simulation to evolve for 500 s, I find that the loop structure collapses after about 150-200 s. I would expect that the loop structure would be maintained at approximately the equilibrium configuration. I've attached a plot below that shows this:

 <https://user-images.githubusercontent.com/8676141/159611013-cd77830d-eb33-4de7-b392-7294b1ddfe8d.png> 

I'm sure I've omitted or misconfigured some input parameter, but I cannot work out which one. I've iterated over all refinement levels (this example uses max refinement level of 12) to ensure that that is not the issue. This is for a semi-circular configuration with no inclination and no exapansion. I've attached the directory for run here as well.

steady-run.zip <https://github.com/rice-solar-physics/HYDRAD/files/8329197/steady-run.zip>

**Comment by wtbarnes** [comment]
I believe so. I'm configuring this via `pydrad` so it seems to be that I'm omitting or messing up some other parameter.

> I’ve just run a 2L = 50 Mm loop, background heating only, and it remains perfectly stable… Are you sure the background heating is being applied?

I believe so. I've pasted my `heating_model.cfg` file below:

```
4.50000000e+09 1.00000000e+300 0.004950962812541607

0


Configuration file generated by pydrad on 2022-03-22_20.25.44 UTC
```

**Comment by wtbarnes** [comment]
I think the 45 Mm was just a leftover value from the defaults. I changed it to 25 Mm without any change.

Is your value of E_H0 = 7.6950E-4 erg cm^-3 s^-1 from the initial conditions solver? I'm getting the following,

```
Calculating initial hydrostatic conditions...

Peak heating range = 4.8978e-03 -> 5.0119e-03 erg cm^-3 s^-1

Optimum peak heating rate = 4.9510e-03 erg cm^-3 s^-1

Writing initial conditions file...

Done!
```

If my heating rate is off by an OOM, that would explain why things aren't stable...

**Comment by sjbradshaw** [comment]
Yes, I get E_H0 = 7.6950E-4 erg cm^-3 s^-1 from the solver for the initial conditions, which is written into the file Initial_Conditions/profiles/initial.amr.sol

 

Are you using the default (power law) radiation calculation?

**Comment by wtbarnes** [comment]
Ok when it comes to the differences in our steady heating rates, the difference seems to be down to the footpoint temperature and density (no surprise). I was using 1e4 K and 1e12 cm-3. Using 2e4 K and 1e11 cm-3 (which are the GUI defaults), I get a stable solution at the same heating rate as you've shown here.

**Comment by sjbradshaw** [comment]
Alright, good, glad that’s resolved! At higher densities / lower temperatures then you may need higher resolution to get a stable solution (or adjust the max. radiation density parameter under the “Solver Tab”).
