### ISSUE TITLE
Rate data still uses CHIANTI v7

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/HYDRAD#97]
While the emissivity data have been updated to use v10 (see #91), the ionization/recombination rate data (https://github.com/rice-solar-physics/HYDRAD/tree/0d10714a116bd0e2d0695f6a756db58cbabffe74/Radiation_Model/atomic_data/rates/chianti_v7) still appear to use CHIANTI v7. 

How easy is it to rebuild these tables for the latest version? Is there a script to do this in HYDRAD already? I'm happy to give it a try, but I'm not completely sure what the format of these files is.

**Comment by sjbradshaw** [comment]
Hi Will,

 

It’s relatively straightforward, just laziness on my part that it hasn’t been done. Actually, it sounds like a good Friday afternoon project, so I’ll have a tinker with it in a bit.

 

Cheers,

 

Steve

 

 

From: Will Barnes ***@***.***> 
Sent: Friday, April 7, 2023 11:38 AM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Rate data still uses CHIANTI v7 (Issue #97)

 

While the emissivity data have been updated to use v10 (see #91 <https://urldefense.com/v3/__https:/github.com/rice-solar-physics/HYDRAD/pull/91__;!!BuQPrrmRaQ!iK2Zv6X7uUdYvcBtZHF1qxwWuscwSd2vC2d27_Tn7S103Sy5AFvEqAgegEGGXUNLoT0ifkMW512pG5uv5JbqMk5tnKtAx8lvu0o$> ), the ionization/recombination rate data (https://github.com/rice-solar-physics/HYDRAD/tree/0d10714a116bd0e2d0695f6a756db58cbabffe74/Radiation_Model/atomic_data/rates/chianti_v7 <https://urldefense.com/v3/__https:/github.com/rice-solar-physics/HYDRAD/tree/0d10714a116bd0e2d0695f6a756db58cbabffe74/Radiation_Model/atomic_data/rates/chianti_v7__;!!BuQPrrmRaQ!iK2Zv6X7uUdYvcBtZHF1qxwWuscwSd2vC2d27_Tn7S103Sy5AFvEqAgegEGGXUNLoT0ifkMW512pG5uv5JbqMk5tnKtAzdfnjc4$> ) still appear to use CHIANTI v7.

How easy is it to rebuild these tables for the latest version? Is there a script to do this in HYDRAD already? I'm happy to give it a try, but I'm not completely sure what the format of these files is.

**Comment by sjbradshaw** [comment]
Now updated in GitHub with Chianti v10 ionization and recombination data. Didn’t take long at all!

 

 

From: Will Barnes ***@***.***> 
Sent: Friday, April 7, 2023 11:38 AM
To: rice-solar-physics/HYDRAD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rice-solar-physics/HYDRAD] Rate data still uses CHIANTI v7 (Issue #97)

 

While the emissivity data have been updated to use v10 (see #91 <https://urldefense.com/v3/__https:/github.com/rice-solar-physics/HYDRAD/pull/91__;!!BuQPrrmRaQ!iK2Zv6X7uUdYvcBtZHF1qxwWuscwSd2vC2d27_Tn7S103Sy5AFvEqAgegEGGXUNLoT0ifkMW512pG5uv5JbqMk5tnKtAx8lvu0o$> ), the ionization/recombination rate data (https://github.com/rice-solar-physics/HYDRAD/tree/0d10714a116bd0e2d0695f6a756db58cbabffe74/Radiation_Model/atomic_data/rates/chianti_v7 <https://urldefense.com/v3/__https:/github.com/rice-solar-physics/HYDRAD/tree/0d10714a116bd0e2d0695f6a756db58cbabffe74/Radiation_Model/atomic_data/rates/chianti_v7__;!!BuQPrrmRaQ!iK2Zv6X7uUdYvcBtZHF1qxwWuscwSd2vC2d27_Tn7S103Sy5AFvEqAgegEGGXUNLoT0ifkMW512pG5uv5JbqMk5tnKtAzdfnjc4$> ) still appear to use CHIANTI v7.

How easy is it to rebuild these tables for the latest version? Is there a script to do this in HYDRAD already? I'm happy to give it a try, but I'm not completely sure what the format of these files is.

**Comment by wtbarnes** [comment]
Wow thanks Steve! That's a record turnaround for a feature!

**Comment by sjbradshaw** [comment]
Honestly, it turned out to be very easy, given the software and utils. I already had available. Thanks for the nudge to get me to actually do it.Sent from my Galaxy
-------- Original message --------From: Will Barnes ***@***.***> Date: 4/7/23  8:30 PM  (GMT-06:00) To: rice-solar-physics/HYDRAD ***@***.***> Cc: sjbradshaw ***@***.***>, Comment ***@***.***> Subject: Re: [rice-solar-physics/HYDRAD] Rate data still uses CHIANTI v7 (Issue #97) 
Wow thanks Steve! That's a record turnaround for a feature!
